# Ames Housing Price Prediction — Data Understanding & Exploratory Data Analysis

## Project Objective

The objective of this project is to develop an end-to-end machine learning system
for predicting house sale prices using the Ames Housing dataset.

The target variable for this project is `SalePrice`.

This notebook focuses on understanding the dataset before performing
data transformation, feature engineering, and model training.

---

## Objectives of This Notebook

In this stage, we will:

1. Understand the structure of the dataset.
2. Identify numerical and categorical features.
3. Understand the target variable.
4. Analyze missing values.
5. Study feature distributions.
6. Identify potential outliers.
7. Analyze relationships between features and the target.
8. Analyze feature correlations.
9. Identify potential multicollinearity.
10. Translate our observations into machine learning decisions.

> Important:
> This notebook is for data understanding and exploration.
> We will not perform permanent data cleaning, feature engineering,
> model training, or model selection in this stage.

## 1. Import Required Libraries

We begin by importing the libraries required for:

- Data manipulation
- Numerical analysis
- Interactive visualization
- File and path handling

We will use Plotly for interactive visualizations throughout the EDA process.

In [27]:
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from pathlib import Path

## 2. Load the Validated Dataset

The dataset used for EDA should come from the output of the Data Ingestion
stage rather than directly from the original raw-data location.

This maintains the separation between pipeline stages:

Raw Dataset
    ↓
Data Ingestion
    ↓
Validated Artifact
    ↓
EDA

Using the ingestion artifact also ensures that our exploratory analysis
is connected to the same data flow that will eventually be used by
the downstream machine learning pipeline.

In [28]:
DATA_PATH = Path(
    "../artifacts/data_ingestion/AmesHousing.txt"
)

df = pd.read_csv(
    DATA_PATH,
    sep="\t"
)
df.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

### Initial Observation

The dataset has been successfully loaded from the Data Ingestion artifact.

The following sections will establish its dimensions, structure, data types,
and statistical characteristics before we begin deeper analysis.

## 3. Dataset Dimensions

Before analyzing individual variables, we first determine the size of the dataset.

The shape of a DataFrame is represented as:

    (number of rows, number of columns)

Rows represent observations, while columns represent variables/features.

Understanding the dataset dimensions provides the baseline for all subsequent
analysis.

In [29]:
df.shape

(2930, 82)

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   MS Zoning        2930 non-null   str
 4   Lot Frontage     2440 non-null   float64
 5   Lot Area         2930 non-null   int64
 6   Street           2930 non-null   str
 7   Alley            198 non-null    str
 8   Lot Shape        2930 non-null   str
 9   Land Contour     2930 non-null   str
 10  Utilities        2930 non-null   str
 11  Lot Config       2930 non-null   str
 12  Land Slope       2930 non-null   str
 13  Neighborhood     2930 non-null   str
 14  Condition 1      2930 non-null   str
 15  Condition 2      2930 non-null   str
 16  Bldg Type        2930 non-null   str
 17  House Style      2930 non-null   str
 18  Overall Qual     2930 non-null   int64
 19  Overall Cond     2930 non-null   int64
 20  Year Built       2930 non-null   int64
 21  Year Remod/Add   2930 non-null   int64
 22  Roof Style       2930 non-null   str
 23  Roof Matl        2930 non-null   str
 24  Exterior 1st     2930 non-null   str
 25  Exterior 2nd     2930 non-null   str
 26  Mas Vnr Type     1155 non-null   str
 27  Mas Vnr Area     2907 non-null   float64
 28  Exter Qual       2930 non-null   str
 29  Exter Cond       2930 non-null   str
 30  Foundation       2930 non-null   str
 31  Bsmt Qual        2850 non-null   str
 32  Bsmt Cond        2850 non-null   str
 33  Bsmt Exposure    2847 non-null   str
 34  BsmtFin Type 1   2850 non-null   str
 35  BsmtFin SF 1     2929 non-null   float64
 36  BsmtFin Type 2   2849 non-null   str
 37  BsmtFin SF 2     2929 non-null   float64
 38  Bsmt Unf SF      2929 non-null   float64
 39  Total Bsmt SF    2929 non-null   float64
 40  Heating          2930 non-null   str
 41  Heating QC       2930 non-null   str
 42  Central Air      2930 non-null   str
 43  Electrical       2929 non-null   str
 44  1st Flr SF       2930 non-null   int64
 45  2nd Flr SF       2930 non-null   int64
 46  Low Qual Fin SF  2930 non-null   int64
 47  Gr Liv Area      2930 non-null   int64
 48  Bsmt Full Bath   2928 non-null   float64
 49  Bsmt Half Bath   2928 non-null   float64
 50  Full Bath        2930 non-null   int64
 51  Half Bath        2930 non-null   int64
 52  Bedroom AbvGr    2930 non-null   int64
 53  Kitchen AbvGr    2930 non-null   int64
 54  Kitchen Qual     2930 non-null   str
 55  TotRms AbvGrd    2930 non-null   int64
 56  Functional       2930 non-null   str
 57  Fireplaces       2930 non-null   int64
 58  Fireplace Qu     1508 non-null   str
 59  Garage Type      2773 non-null   str
 60  Garage Yr Blt    2771 non-null   float64
 61  Garage Finish    2771 non-null   str
 62  Garage Cars      2929 non-null   float64
 63  Garage Area      2929 non-null   float64
 64  Garage Qual      2771 non-null   str
 65  Garage Cond      2771 non-null   str
 66  Paved Drive      2930 non-null   str
 67  Wood Deck SF     2930 non-null   int64
 68  Open Porch SF    2930 non-null   int64
 69  Enclosed Porch   2930 non-null   int64
 70  3Ssn Porch       2930 non-null   int64
 71  Screen Porch     2930 non-null   int64
 72  Pool Area        2930 non-null   int64
 73  Pool QC          13 non-null     str
 74  Fence            572 non-null    str
 75  Misc Feature     106 non-null    str
 76  Misc Val         2930 non-null   int64
 77  Mo Sold          2930 non-null   int64
 78  Yr Sold          2930 non-null   int64
 79  Sale Type        2930 non-null   str
 80  Sale Condition   2930 non-null   str
 81  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), str(43)
memory usage: 1.8 MB

### Interpretation

The dataset contains **2930 observations** and **82 columns**.

Each row represents one housing observation, while the columns contain
characteristics associated with the property and its sale.

The target variable `SalePrice` is included among these columns.

The dataset contains both numerical and categorical information.

At this point, we are only observing the raw structure.
We are not modifying any values.

In [31]:
numerical_columns = (
    df.select_dtypes(
        include=np.number
    ).columns.tolist()
)

categorical_columns = (
    df.select_dtypes(
        exclude=np.number
    ).columns.tolist()
)

In [32]:
print(
    "Numerical columns:",
    len(numerical_columns)
)

print(
    "Categorical columns:",
    len(categorical_columns)
)

Numerical columns: 39
Categorical columns: 43

In [33]:
print(numerical_columns)

['Order', 'PID', 'MS SubClass', 'Lot Frontage', 'Lot Area', 'Overall Qual', 'Overall Cond', 'Year Built', 'Year Remod/Add', 'Mas Vnr Area', 'BsmtFin SF 1', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Full Bath', 'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'TotRms AbvGrd', 'Fireplaces', 'Garage Yr Blt', 'Garage Cars', 'Garage Area', 'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Misc Val', 'Mo Sold', 'Yr Sold', 'SalePrice']

In [34]:
print(categorical_columns)

['MS Zoning', 'Street', 'Alley', 'Lot Shape', 'Land Contour', 'Utilities', 'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1', 'Condition 2', 'Bldg Type', 'House Style', 'Roof Style', 'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type', 'Exter Qual', 'Exter Cond', 'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin Type 2', 'Heating', 'Heating QC', 'Central Air', 'Electrical', 'Kitchen Qual', 'Functional', 'Fireplace Qu', 'Garage Type', 'Garage Finish', 'Garage Qual', 'Garage Cond', 'Paved Drive', 'Pool QC', 'Fence', 'Misc Feature', 'Sale Type', 'Sale Condition']

In [35]:
target = df["SalePrice"]

In [36]:
target.describe()

count      2930.000000
mean     180796.060068
std       79886.692357
min       12789.000000
25%      129500.000000
50%      160000.000000
75%      213500.000000
max      755000.000000
Name: SalePrice, dtype: float64

In [37]:
fig = px.histogram(
    df,
    x="SalePrice",
    nbins=50,
    title="Distribution of SalePrice"
)

fig.show()

In [38]:
target_skewness = df["SalePrice"].skew()

print(
    "SalePrice skewness:",
    target_skewness
)

SalePrice skewness: 1.7435000757376466

In [39]:
fig = px.box(
    df,
    y="SalePrice",
    title="SalePrice Box Plot"
)

fig.show()

### Interpretation

The `SalePrice` distribution shows evidence of right skewness.

This observation is consistent with the presence of relatively expensive
properties that extend the upper tail of the distribution.

We will not transform the target yet. The decision to apply a transformation
will be made later after considering the requirements and assumptions of
the models we evaluate.

In [40]:
missing_summary = (
    df.isna()
      .sum()
      .sort_values(
          ascending=False
      )
)

missing_summary = (
    missing_summary[
        missing_summary > 0
    ]
)

missing_summary

Pool QC           2917
Misc Feature      2824
Alley             2732
Fence             2358
Mas Vnr Type      1775
Fireplace Qu      1422
Lot Frontage       490
Garage Qual        159
Garage Yr Blt      159
Garage Cond        159
Garage Finish      159
Garage Type        157
Bsmt Exposure       83
BsmtFin Type 2      81
Bsmt Qual           80
Bsmt Cond           80
BsmtFin Type 1      80
Mas Vnr Area        23
Bsmt Full Bath       2
Bsmt Half Bath       2
Total Bsmt SF        1
BsmtFin SF 1         1
BsmtFin SF 2         1
Garage Area          1
Garage Cars          1
Bsmt Unf SF          1
Electrical           1
dtype: int64

In [41]:
missing_percentage = (
    df.isna().mean() * 100
)

missing_percentage = (
    missing_percentage[
        missing_percentage > 0
    ]
    .sort_values(
        ascending=False
    )
)

missing_percentage

Pool QC           99.556314
Misc Feature      96.382253
Alley             93.242321
Fence             80.477816
Mas Vnr Type      60.580205
Fireplace Qu      48.532423
Lot Frontage      16.723549
Garage Qual        5.426621
Garage Cond        5.426621
Garage Yr Blt      5.426621
Garage Finish      5.426621
Garage Type        5.358362
Bsmt Exposure      2.832765
BsmtFin Type 2     2.764505
Bsmt Cond          2.730375
Bsmt Qual          2.730375
BsmtFin Type 1     2.730375
Mas Vnr Area       0.784983
Bsmt Full Bath     0.068259
Bsmt Half Bath     0.068259
BsmtFin SF 1       0.034130
BsmtFin SF 2       0.034130
Electrical         0.034130
Total Bsmt SF      0.034130
Bsmt Unf SF        0.034130
Garage Area        0.034130
Garage Cars        0.034130
dtype: float64

In [42]:
missing_plot = (
    missing_percentage
    .reset_index()
)

missing_plot.columns = [
    "Feature",
    "MissingPercentage"
]

fig = px.bar(
    missing_plot,
    x="MissingPercentage",
    y="Feature",
    orientation="h",
    title="Missing Values by Feature"
)

fig.show()

In [43]:
selected_numeric = [
    "SalePrice",
    "Gr Liv Area",
    "Total Bsmt SF",
    "Garage Area",
    "Year Built",
]
for column in selected_numeric:

    fig = px.histogram(
        df,
        x=column,
        nbins=40,
        title=f"Distribution of {column}"
    )

    fig.show()

In [44]:
numerical_features = [
    column
    for column in numerical_columns
    if column != "SalePrice"
]

print(
    "Number of numerical predictor features:",
    len(numerical_features)
)

Number of numerical predictor features: 38

In [45]:
numerical_summary = (
    df[numerical_features]
    .describe()
    .T
)

numerical_summary

,count,mean,std,min,25%,50%,75%,max
Order,2930.0,1.465500e+03,8.459625e+02,1.0,7.332500e+02,1465.5,2.197750e+03,2.930000e+03
PID,2930.0,7.144645e+08,1.887308e+08,526301100.0,5.284770e+08,535453620.0,9.071811e+08,1.007100e+09
MS SubClass,2930.0,5.738737e+01,4.263802e+01,20.0,2.000000e+01,50.0,7.000000e+01,1.900000e+02
Lot Frontage,2440.0,6.922459e+01,2.336533e+01,21.0,5.800000e+01,68.0,8.000000e+01,3.130000e+02
Lot Area,2930.0,1.014792e+04,7.880018e+03,1300.0,7.440250e+03,9436.5,1.155525e+04,2.152450e+05
Overall Qual,2930.0,6.094881e+00,1.411026e+00,1.0,5.000000e+00,6.0,7.000000e+00,1.000000e+01
Overall Cond,2930.0,5.563140e+00,1.111537e+00,1.0,5.000000e+00,5.0,6.000000e+00,9.000000e+00
Year Built,2930.0,1.971356e+03,3.024536e+01,1872.0,1.954000e+03,1973.0,2.001000e+03,2.010000e+03
Year Remod/Add,2930.0,1.984267e+03,2.086029e+01,1950.0,1.965000e+03,1993.0,2.004000e+03,2.010000e+03
Mas Vnr Area,2907.0,1.018968e+02,1.791126e+02,0.0,0.000000e+00,0.0,1.640000e+02,1.600000e+03
BsmtFin SF 1,2929.0,4.426296e+02,4.555908e+02,0.0,0.000000e+00,370.0,7.340000e+02,5.644000e+03
BsmtFin SF 2,2929.0,4.972243e+01,1.691685e+02,0.0,0.000000e+00,0.0,0.000000e+00,1.526000e+03
Bsmt Unf SF,2929.0,5.592625e+02,4.394942e+02,0.0,2.190000e+02,466.0,8.020000e+02,2.336000e+03
Total Bsmt SF,2929.0,1.051615e+03,4.406151e+02,0.0,7.930000e+02,990.0,1.302000e+03,6.110000e+03
1st Flr SF,2930.0,1.159558e+03,3.918909e+02,334.0,8.762500e+02,1084.0,1.384000e+03,5.095000e+03
2nd Flr SF,2930.0,3.354560e+02,4.283957e+02,0.0,0.000000e+00,0.0,7.037500e+02,2.065000e+03
Low Qual Fin SF,2930.0,4.676792e+00,4.631051e+01,0.0,0.000000e+00,0.0,0.000000e+00,1.064000e+03
Gr Liv Area,2930.0,1.499690e+03,5.055089e+02,334.0,1.126000e+03,1442.0,1.742750e+03,5.642000e+03
Bsmt Full Bath,2928.0,4.313525e-01,5.248202e-01,0.0,0.000000e+00,0.0,1.000000e+00,3.000000e+00
Bsmt Half Bath,2928.0,6.113388e-02,2.452536e-01,0.0,0.000000e+00,0.0,0.000000e+00,2.000000e+00
Full Bath,2930.0,1.566553e+00,5.529406e-01,0.0,1.000000e+00,2.0,2.000000e+00,4.000000e+00
Half Bath,2930.0,3.795222e-01,5.026293e-01,0.0,0.000000e+00,0.0,1.000000e+00,2.000000e+00
Bedroom AbvGr,2930.0,2.854266e+00,8.277311e-01,0.0,2.000000e+00,3.0,3.000000e+00,8.000000e+00
Kitchen AbvGr,2930.0,1.044369e+00,2.140762e-01,0.0,1.000000e+00,1.0,1.000000e+00,3.000000e+00
TotRms AbvGrd,2930.0,6.443003e+00,1.572964e+00,2.0,5.000000e+00,6.0,7.000000e+00,1.500000e+01
Fireplaces,2930.0,5.993174e-01,6.479209e-01,0.0,0.000000e+00,1.0,1.000000e+00,4.000000e+00
Garage Yr Blt,2771.0,1.978132e+03,2.552841e+01,1895.0,1.960000e+03,1979.0,2.002000e+03,2.207000e+03
Garage Cars,2929.0,1.766815e+00,7.605664e-01,0.0,1.000000e+00,2.0,2.000000e+00,5.000000e+00
Garage Area,2929.0,4.728197e+02,2.150465e+02,0.0,3.200000e+02,480.0,5.760000e+02,1.488000e+03
Wood Deck SF,2930.0,9.375188e+01,1.263616e+02,0.0,0.000000e+00,0.0,1.680000e+02,1.424000e+03
Open Porch SF,2930.0,4.753345e+01,6.748340e+01,0.0,0.000000e+00,27.0,7.000000e+01,7.420000e+02
Enclosed Porch,2930.0,2.301160e+01,6.413906e+01,0.0,0.000000e+00,0.0,0.000000e+00,1.012000e+03
3Ssn Porch,2930.0,2.592491e+00,2.514133e+01,0.0,0.000000e+00,0.0,0.000000e+00,5.080000e+02
Screen Porch,2930.0,1.600205e+01,5.608737e+01,0.0,0.000000e+00,0.0,0.000000e+00,5.760000e+02
Pool Area,2930.0,2.243345e+00,3.559718e+01,0.0,0.000000e+00,0.0,0.000000e+00,8.000000e+02
Misc Val,2930.0,5.063515e+01,5.663443e+02,0.0,0.000000e+00,0.0,0.000000e+00,1.700000e+04
Mo Sold,2930.0,6.216041e+00,2.714492e+00,1.0,4.000000e+00,6.0,8.000000e+00,1.200000e+01
Yr Sold,2930.0,2.007790e+03,1.316613e+00,2006.0,2.007000e+03,2008.0,2.009000e+03,2.010000e+03

In [46]:
numerical_summary["IQR"] = (
    numerical_summary["75%"]
    - numerical_summary["25%"]
)

numerical_summary[
    [
        "mean",
        "50%",
        "std",
        "min",
        "25%",
        "75%",
        "max",
        "IQR",
    ]
]

,mean,50%,std,min,25%,75%,max,IQR
Order,1.465500e+03,1465.5,8.459625e+02,1.0,7.332500e+02,2.197750e+03,2.930000e+03,1.464500e+03
PID,7.144645e+08,535453620.0,1.887308e+08,526301100.0,5.284770e+08,9.071811e+08,1.007100e+09,3.787041e+08
MS SubClass,5.738737e+01,50.0,4.263802e+01,20.0,2.000000e+01,7.000000e+01,1.900000e+02,5.000000e+01
Lot Frontage,6.922459e+01,68.0,2.336533e+01,21.0,5.800000e+01,8.000000e+01,3.130000e+02,2.200000e+01
Lot Area,1.014792e+04,9436.5,7.880018e+03,1300.0,7.440250e+03,1.155525e+04,2.152450e+05,4.115000e+03
Overall Qual,6.094881e+00,6.0,1.411026e+00,1.0,5.000000e+00,7.000000e+00,1.000000e+01,2.000000e+00
Overall Cond,5.563140e+00,5.0,1.111537e+00,1.0,5.000000e+00,6.000000e+00,9.000000e+00,1.000000e+00
Year Built,1.971356e+03,1973.0,3.024536e+01,1872.0,1.954000e+03,2.001000e+03,2.010000e+03,4.700000e+01
Year Remod/Add,1.984267e+03,1993.0,2.086029e+01,1950.0,1.965000e+03,2.004000e+03,2.010000e+03,3.900000e+01
Mas Vnr Area,1.018968e+02,0.0,1.791126e+02,0.0,0.000000e+00,1.640000e+02,1.600000e+03,1.640000e+02
BsmtFin SF 1,4.426296e+02,370.0,4.555908e+02,0.0,0.000000e+00,7.340000e+02,5.644000e+03,7.340000e+02
BsmtFin SF 2,4.972243e+01,0.0,1.691685e+02,0.0,0.000000e+00,0.000000e+00,1.526000e+03,0.000000e+00
Bsmt Unf SF,5.592625e+02,466.0,4.394942e+02,0.0,2.190000e+02,8.020000e+02,2.336000e+03,5.830000e+02
Total Bsmt SF,1.051615e+03,990.0,4.406151e+02,0.0,7.930000e+02,1.302000e+03,6.110000e+03,5.090000e+02
1st Flr SF,1.159558e+03,1084.0,3.918909e+02,334.0,8.762500e+02,1.384000e+03,5.095000e+03,5.077500e+02
2nd Flr SF,3.354560e+02,0.0,4.283957e+02,0.0,0.000000e+00,7.037500e+02,2.065000e+03,7.037500e+02
Low Qual Fin SF,4.676792e+00,0.0,4.631051e+01,0.0,0.000000e+00,0.000000e+00,1.064000e+03,0.000000e+00
Gr Liv Area,1.499690e+03,1442.0,5.055089e+02,334.0,1.126000e+03,1.742750e+03,5.642000e+03,6.167500e+02
Bsmt Full Bath,4.313525e-01,0.0,5.248202e-01,0.0,0.000000e+00,1.000000e+00,3.000000e+00,1.000000e+00
Bsmt Half Bath,6.113388e-02,0.0,2.452536e-01,0.0,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00
Full Bath,1.566553e+00,2.0,5.529406e-01,0.0,1.000000e+00,2.000000e+00,4.000000e+00,1.000000e+00
Half Bath,3.795222e-01,0.0,5.026293e-01,0.0,0.000000e+00,1.000000e+00,2.000000e+00,1.000000e+00
Bedroom AbvGr,2.854266e+00,3.0,8.277311e-01,0.0,2.000000e+00,3.000000e+00,8.000000e+00,1.000000e+00
Kitchen AbvGr,1.044369e+00,1.0,2.140762e-01,0.0,1.000000e+00,1.000000e+00,3.000000e+00,0.000000e+00
TotRms AbvGrd,6.443003e+00,6.0,1.572964e+00,2.0,5.000000e+00,7.000000e+00,1.500000e+01,2.000000e+00
Fireplaces,5.993174e-01,1.0,6.479209e-01,0.0,0.000000e+00,1.000000e+00,4.000000e+00,1.000000e+00
Garage Yr Blt,1.978132e+03,1979.0,2.552841e+01,1895.0,1.960000e+03,2.002000e+03,2.207000e+03,4.200000e+01
Garage Cars,1.766815e+00,2.0,7.605664e-01,0.0,1.000000e+00,2.000000e+00,5.000000e+00,1.000000e+00
Garage Area,4.728197e+02,480.0,2.150465e+02,0.0,3.200000e+02,5.760000e+02,1.488000e+03,2.560000e+02
Wood Deck SF,9.375188e+01,0.0,1.263616e+02,0.0,0.000000e+00,1.680000e+02,1.424000e+03,1.680000e+02
Open Porch SF,4.753345e+01,27.0,6.748340e+01,0.0,0.000000e+00,7.000000e+01,7.420000e+02,7.000000e+01
Enclosed Porch,2.301160e+01,0.0,6.413906e+01,0.0,0.000000e+00,0.000000e+00,1.012000e+03,0.000000e+00
3Ssn Porch,2.592491e+00,0.0,2.514133e+01,0.0,0.000000e+00,0.000000e+00,5.080000e+02,0.000000e+00
Screen Porch,1.600205e+01,0.0,5.608737e+01,0.0,0.000000e+00,0.000000e+00,5.760000e+02,0.000000e+00
Pool Area,2.243345e+00,0.0,3.559718e+01,0.0,0.000000e+00,0.000000e+00,8.000000e+02,0.000000e+00
Misc Val,5.063515e+01,0.0,5.663443e+02,0.0,0.000000e+00,0.000000e+00,1.700000e+04,0.000000e+00
Mo Sold,6.216041e+00,6.0,2.714492e+00,1.0,4.000000e+00,8.000000e+00,1.200000e+01,4.000000e+00
Yr Sold,2.007790e+03,2008.0,1.316613e+00,2006.0,2.007000e+03,2.009000e+03,2.010000e+03,2.000000e+00

In [47]:
for column in numerical_features:

    fig = px.histogram(
        df,
        x=column,
        nbins=40,
        title=f"Distribution of {column}"
    )

    fig.show()

In [48]:
for column in numerical_features:

    fig = px.box(
        df,
        y=column,
        title=f"Box Plot of {column}"
    )

    fig.show()

In [49]:
outlier_summary = []

for column in numerical_features:

    q1 = df[column].quantile(0.25)
    q3 = df[column].quantile(0.75)

    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outlier_count = (
        (df[column] < lower_bound)
        | (df[column] > upper_bound)
    ).sum()

    outlier_percentage = (
        outlier_count / len(df) * 100
    )

    outlier_summary.append(
        {
            "Feature": column,
            "Q1": q1,
            "Q3": q3,
            "IQR": iqr,
            "LowerBound": lower_bound,
            "UpperBound": upper_bound,
            "OutlierCount": outlier_count,
            "OutlierPercentage": outlier_percentage,
        }
    )

outlier_summary = pd.DataFrame(
    outlier_summary
)

outlier_summary.sort_values(
    "OutlierPercentage",
    ascending=False
)

,Feature,Q1,Q3,IQR,LowerBound,UpperBound,OutlierCount,OutlierPercentage
31,Enclosed Porch,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,459,15.665529
11,BsmtFin SF 2,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,351,11.979522
33,Screen Porch,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,256,8.737201
6,Overall Cond,5.000000e+00,6.000000e+00,1.000000e+00,3.500000e+00,7.500000e+00,252,8.600683
2,MS SubClass,2.000000e+01,7.000000e+01,5.000000e+01,-5.500000e+01,1.450000e+02,208,7.098976
9,Mas Vnr Area,0.000000e+00,1.640000e+02,1.640000e+02,-2.460000e+02,4.100000e+02,200,6.825939
3,Lot Frontage,5.800000e+01,8.000000e+01,2.200000e+01,2.500000e+01,1.130000e+02,187,6.382253
19,Bsmt Half Bath,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,175,5.972696
30,Open Porch SF,0.000000e+00,7.000000e+01,7.000000e+01,-1.050000e+02,1.750000e+02,159,5.426621
23,Kitchen AbvGr,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,134,4.573379
4,Lot Area,7.440250e+03,1.155525e+04,4.115000e+03,1.267750e+03,1.772775e+04,127,4.334471
13,Total Bsmt SF,7.930000e+02,1.302000e+03,5.090000e+02,2.950000e+01,2.065500e+03,123,4.197952
35,Misc Val,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,103,3.515358
22,Bedroom AbvGr,2.000000e+00,3.000000e+00,1.000000e+00,5.000000e-01,4.500000e+00,78,2.662116
17,Gr Liv Area,1.126000e+03,1.742750e+03,6.167500e+02,2.008750e+02,2.667875e+03,75,2.559727
29,Wood Deck SF,0.000000e+00,1.680000e+02,1.680000e+02,-2.520000e+02,4.200000e+02,67,2.286689
12,Bsmt Unf SF,2.190000e+02,8.020000e+02,5.830000e+02,-6.555000e+02,1.676500e+03,56,1.911263
24,TotRms AbvGrd,5.000000e+00,7.000000e+00,2.000000e+00,2.000000e+00,1.000000e+01,51,1.740614
14,1st Flr SF,8.762500e+02,1.384000e+03,5.077500e+02,1.146250e+02,2.145625e+03,43,1.467577
28,Garage Area,3.200000e+02,5.760000e+02,2.560000e+02,-6.400000e+01,9.600000e+02,42,1.433447
16,Low Qual Fin SF,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,40,1.365188
32,3Ssn Porch,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,37,1.262799
27,Garage Cars,1.000000e+00,2.000000e+00,1.000000e+00,-5.000000e-01,3.500000e+00,17,0.580205
10,BsmtFin SF 1,0.000000e+00,7.340000e+02,7.340000e+02,-1.101000e+03,1.835000e+03,15,0.511945
34,Pool Area,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,13,0.443686
25,Fireplaces,0.000000e+00,1.000000e+00,1.000000e+00,-1.500000e+00,2.500000e+00,13,0.443686
7,Year Built,1.954000e+03,2.001000e+03,4.700000e+01,1.883500e+03,2.071500e+03,9,0.307167
15,2nd Flr SF,0.000000e+00,7.037500e+02,7.037500e+02,-1.055625e+03,1.759375e+03,8,0.273038
5,Overall Qual,5.000000e+00,7.000000e+00,2.000000e+00,2.000000e+00,1.000000e+01,4,0.136519
20,Full Bath,1.000000e+00,2.000000e+00,1.000000e+00,-5.000000e-01,3.500000e+00,4,0.136519
26,Garage Yr Blt,1.960000e+03,2.002000e+03,4.200000e+01,1.897000e+03,2.065000e+03,3,0.102389
18,Bsmt Full Bath,0.000000e+00,1.000000e+00,1.000000e+00,-1.500000e+00,2.500000e+00,2,0.068259
0,Order,7.332500e+02,2.197750e+03,1.464500e+03,-1.463500e+03,4.394500e+03,0,0.000000
1,PID,5.284770e+08,9.071811e+08,3.787041e+08,-3.957909e+07,1.475237e+09,0,0.000000
21,Half Bath,0.000000e+00,1.000000e+00,1.000000e+00,-1.500000e+00,2.500000e+00,0,0.000000
8,Year Remod/Add,1.965000e+03,2.004000e+03,3.900000e+01,1.906500e+03,2.062500e+03,0,0.000000
36,Mo Sold,4.000000e+00,8.000000e+00,4.000000e+00,-2.000000e+00,1.400000e+01,0,0.000000
37,Yr Sold,2.007000e+03,2.009000e+03,2.000000e+00,2.004000e+03,2.012000e+03,0,0.000000

In [51]:
df['Gr Liv Area'].describe()

count    2930.000000
mean     1499.690444
std       505.508887
min       334.000000
25%      1126.000000
50%      1442.000000
75%      1742.750000
max      5642.000000
Name: Gr Liv Area, dtype: float64

In [53]:
feature = "Gr Liv Area"

fig = px.scatter(
    df,
    x=feature,
    y="SalePrice",
    title=f"{feature} vs SalePrice",
    trendline="ols"
)

fig.show()

### Interpretation

`Gr Liv Area` shows a positive relationship with `SalePrice`.

As above-ground living area increases, sale price generally tends to
increase.

However, the observations do not fall exactly on a straight line.
There is considerable variation in sale price for houses with similar
living areas.

This indicates that living area alone cannot completely explain
house prices.

Other characteristics such as quality, location, age, garage,
basement, and other property attributes may also contribute to
the final sale price.

In [54]:
covariance = df[
    ["Gr Liv Area", "SalePrice"]
].cov()

covariance

              Gr Liv Area     SalePrice
Gr Liv Area  2.555392e+05  2.854220e+07
SalePrice    2.854220e+07  6.381884e+09

In [55]:
numerical_target_correlation = (
    df[numerical_features + ["SalePrice"]]
    .corr()["SalePrice"]
    .drop("SalePrice")
    .sort_values(
        ascending=False
    )
)

numerical_target_correlation

Overall Qual       0.799262
Gr Liv Area        0.706780
Garage Cars        0.647877
Garage Area        0.640401
Total Bsmt SF      0.632280
1st Flr SF         0.621676
Year Built         0.558426
Full Bath          0.545604
Year Remod/Add     0.532974
Garage Yr Blt      0.526965
Mas Vnr Area       0.508285
TotRms AbvGrd      0.495474
Fireplaces         0.474558
BsmtFin SF 1       0.432914
Lot Frontage       0.357318
Wood Deck SF       0.327143
Open Porch SF      0.312951
Half Bath          0.285056
Bsmt Full Bath     0.276050
2nd Flr SF         0.269373
Lot Area           0.266549
Bsmt Unf SF        0.182855
Bedroom AbvGr      0.143913
Screen Porch       0.112151
Pool Area          0.068403
Mo Sold            0.035259
3Ssn Porch         0.032225
BsmtFin SF 2       0.005891
Misc Val          -0.015691
Yr Sold           -0.030569
Order             -0.031408
Bsmt Half Bath    -0.035835
Low Qual Fin SF   -0.037660
MS SubClass       -0.085092
Overall Cond      -0.101697
Kitchen AbvGr     -0.119814
Enclosed Porch    -0.128787
PID               -0.246521
Name: SalePrice, dtype: float64

In [56]:
correlation_plot = (
    numerical_target_correlation
    .reset_index()
)

correlation_plot.columns = [
    "Feature",
    "Correlation"
]

fig = px.bar(
    correlation_plot,
    x="Correlation",
    y="Feature",
    orientation="h",
    title="Numerical Feature Correlation with SalePrice"
)

fig.show()

In [57]:
top_correlations = (
    numerical_target_correlation
    .abs()
    .sort_values(
        ascending=False
    )
    .head(10)
)

top_correlations

Overall Qual      0.799262
Gr Liv Area       0.706780
Garage Cars       0.647877
Garage Area       0.640401
Total Bsmt SF     0.632280
1st Flr SF        0.621676
Year Built        0.558426
Full Bath         0.545604
Year Remod/Add    0.532974
Garage Yr Blt     0.526965
Name: SalePrice, dtype: float64

In [58]:
top_features = (
    top_correlations.index
)

df[
    list(top_features) + ["SalePrice"]
].corr()["SalePrice"].sort_values(
    ascending=False
)

SalePrice         1.000000
Overall Qual      0.799262
Gr Liv Area       0.706780
Garage Cars       0.647877
Garage Area       0.640401
Total Bsmt SF     0.632280
1st Flr SF        0.621676
Year Built        0.558426
Full Bath         0.545604
Year Remod/Add    0.532974
Garage Yr Blt     0.526965
Name: SalePrice, dtype: float64

In [59]:
for feature in top_features:

    fig = px.scatter(
        df,
        x=feature,
        y="SalePrice",
        title=f"{feature} vs SalePrice",
        trendline="ols"
    )

    fig.show()

In [61]:
covariance = df[
    ["Gr Liv Area", "SalePrice"]
].cov()

covariance

              Gr Liv Area     SalePrice
Gr Liv Area  2.555392e+05  2.854220e+07
SalePrice    2.854220e+07  6.381884e+09

In [64]:
feature_correlation = (
    df[numerical_features]
    .corr()
)

feature_correlation

,Order,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,...,Garage Area,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold
Order,1.000000,0.173593,0.011797,-0.007034,0.031354,-0.048500,-0.011054,-0.052319,-0.075566,-0.030907,...,-0.035435,-0.011292,0.016355,0.027908,-0.024975,0.004307,0.052518,-0.006083,0.133365,-0.975993
PID,0.173593,1.000000,-0.001281,-0.096918,0.034868,-0.263147,0.104451,-0.343388,-0.157111,-0.229283,...,-0.210606,-0.051135,-0.071311,0.162519,-0.024894,-0.025735,-0.002845,-0.008260,-0.050455,0.009579
MS SubClass,0.011797,-0.001281,1.000000,-0.420135,-0.204613,0.039419,-0.067349,0.036579,0.043397,0.002730,...,-0.103239,-0.017310,-0.014823,-0.022866,-0.037956,-0.050614,-0.003434,-0.029254,0.000350,-0.017905
Lot Frontage,-0.007034,-0.096918,-0.420135,1.000000,0.491313,0.212042,-0.074448,0.121562,0.091712,0.222407,...,0.358505,0.120084,0.163040,0.012758,0.028564,0.076666,0.173947,0.044476,0.011085,-0.007547
Lot Area,0.031354,0.034868,-0.204613,0.491313,1.000000,0.097188,-0.034759,0.023258,0.021682,0.126830,...,0.212822,0.157212,0.103760,0.021868,0.016243,0.055044,0.093775,0.069188,0.003859,-0.023085
Overall Qual,-0.048500,-0.263147,0.039419,0.212042,0.097188,1.000000,-0.094812,0.597027,0.569609,0.429418,...,0.563503,0.255663,0.298412,-0.140332,0.018240,0.041615,0.030399,0.005179,0.031103,-0.020719
Overall Cond,-0.011054,0.104451,-0.067349,-0.074448,-0.034759,-0.094812,1.000000,-0.368773,0.047680,-0.135340,...,-0.153754,0.020344,-0.068934,0.071459,0.043852,0.044055,-0.016787,0.034056,-0.007295,0.031207
Year Built,-0.052319,-0.343388,0.036579,0.121562,0.023258,0.597027,-0.368773,1.000000,0.612095,0.313292,...,0.480131,0.228964,0.198365,-0.374364,0.015803,-0.041436,0.002213,-0.011011,0.014577,-0.013197
Year Remod/Add,-0.075566,-0.157111,0.043397,0.091712,0.021682,0.569609,0.047680,0.612095,1.000000,0.196928,...,0.376438,0.217857,0.241748,-0.220383,0.037412,-0.046888,-0.011410,-0.003132,0.018048,0.032652
Mas Vnr Area,-0.030907,-0.229283,0.002730,0.222407,0.126830,0.429418,-0.135340,0.313292,0.196928,1.000000,...,0.373458,0.165467,0.143748,-0.110787,0.013778,0.065643,0.004617,0.044934,-0.000276,-0.017715
BsmtFin SF 1,-0.032321,-0.098375,-0.060075,0.215583,0.191555,0.284118,-0.050935,0.279870,0.151790,0.301872,...,0.309876,0.224010,0.124947,-0.100455,0.050541,0.095874,0.084140,0.092886,-0.001155,0.022397
BsmtFin SF 2,-0.002773,-0.001145,-0.070946,0.045999,0.083150,-0.041287,0.041134,-0.027415,-0.062129,-0.016019,...,0.003318,0.098528,-0.005587,0.032380,-0.023325,0.062951,0.044398,-0.005204,-0.009484,0.007105
Bsmt Unf SF,0.005780,-0.087707,-0.130421,0.116743,0.023658,0.270058,-0.136819,0.128998,0.164805,0.091668,...,0.164236,-0.039621,0.118880,0.006229,-0.005446,-0.048083,-0.031999,-0.010166,0.021569,-0.036384
Total Bsmt SF,-0.028719,-0.189642,-0.219445,0.353773,0.253589,0.547294,-0.173344,0.407526,0.297481,0.397040,...,0.485504,0.229931,0.245627,-0.085225,0.037871,0.075341,0.072128,0.083904,0.016678,-0.010405
1st Flr SF,-0.013201,-0.141902,-0.247828,0.457391,0.332235,0.477837,-0.157052,0.310463,0.242108,0.395736,...,0.491223,0.227131,0.238041,-0.065713,0.044061,0.098316,0.121821,0.093003,0.040496,-0.013667
2nd Flr SF,-0.000417,-0.003289,0.304237,0.029187,0.032996,0.241402,0.006218,0.016828,0.158939,0.121805,...,0.128614,0.089097,0.184538,0.055429,-0.032172,0.011741,0.044602,-0.005078,0.013247,-0.018530
Low Qual Fin SF,0.013589,0.056940,0.025765,0.005249,0.000812,-0.048680,0.009175,-0.144282,-0.060365,-0.057701,...,-0.053510,-0.015646,-0.000761,0.087326,-0.004505,0.006943,0.035200,-0.005939,0.011397,-0.002074
Gr Liv Area,-0.009342,-0.107579,0.068061,0.383822,0.285599,0.570556,-0.115643,0.241726,0.316855,0.403611,...,0.484892,0.250153,0.340857,0.004030,0.006481,0.086804,0.135463,0.067252,0.043665,-0.026489
Bsmt Full Bath,-0.042539,-0.037759,0.013701,0.108915,0.125877,0.167858,-0.042766,0.211849,0.134387,0.140113,...,0.184489,0.186945,0.082268,-0.069235,0.027034,0.052208,0.043705,-0.004868,-0.003471,0.044905
Bsmt Half Bath,0.024978,0.004328,-0.003329,-0.024724,0.026903,-0.041647,0.084455,-0.030626,-0.046292,0.015421,...,-0.021373,0.051430,-0.035069,-0.009334,0.026954,0.042326,0.066902,0.036982,0.022699,-0.019529
Full Bath,-0.044985,-0.171431,0.134631,0.184521,0.127433,0.522263,-0.214316,0.469406,0.457266,0.260153,...,0.407464,0.179574,0.258675,-0.117795,0.015435,-0.015130,0.028205,-0.009771,0.046032,-0.004754
Half Bath,-0.039749,-0.166636,0.175879,0.041880,0.035497,0.268853,-0.088127,0.269268,0.211771,0.192965,...,0.178332,0.115212,0.180704,-0.081312,-0.023231,0.035990,0.001515,0.026648,-0.001311,0.001561
Bedroom AbvGr,0.015424,0.006345,-0.019208,0.240442,0.136569,0.063291,-0.006137,-0.055093,-0.021536,0.080546,...,0.073610,0.029711,0.083650,0.052115,-0.047151,0.009250,0.036707,0.000887,0.053677,-0.018008
Kitchen AbvGr,-0.017685,0.076470,0.257698,0.005407,-0.020301,-0.159744,-0.086386,-0.137852,-0.142404,-0.050998,...,-0.057779,-0.087410,-0.068283,0.027911,-0.021379,-0.056337,-0.013066,0.025145,0.035201,0.035421
TotRms AbvGrd,0.002612,-0.068981,0.031898,0.353137,0.216597,0.380693,-0.089816,0.111919,0.197528,0.279563,...,0.327280,0.154735,0.235684,0.017221,-0.025097,0.033731,0.072103,0.061134,0.043784,-0.030498
Fireplaces,-0.019156,-0.108056,-0.049955,0.257255,0.256989,0.393007,-0.031702,0.170672,0.133322,0.272068,...,0.293853,0.228064,0.159637,-0.000250,0.018414,0.168004,0.098449,0.008192,0.032152,-0.007612
Garage Yr Blt,-0.051160,-0.256829,0.088754,0.076306,-0.008952,0.570569,-0.326017,0.834849,0.652310,0.254784,...,0.555019,0.221991,0.231240,-0.300879,0.020617,-0.062515,-0.014513,-0.009265,0.024498,-0.005159
Garage Cars,-0.036185,-0.237484,-0.045883,0.308706,0.179512,0.599545,-0.181557,0.537443,0.425403,0.360159,...,0.889676,0.241226,0.204182,-0.132840,0.023345,0.043012,0.030393,-0.016948,0.049847,-0.022488
Garage Area,-0.035435,-0.210606,-0.103239,0.358505,0.212822,0.563503,-0.153754,0.480131,0.376438,0.373458,...,1.000000,0.238371,0.232912,-0.106272,0.029458,0.062436,0.053051,0.008466,0.039544,-0.013018
Wood Deck SF,-0.011292,-0.051135,-0.017310,0.120084,0.157212,0.255663,0.020344,0.228964,0.217857,0.165467,...,0.238371,1.000000,0.039243,-0.119136,-0.003967,-0.052191,0.094156,0.056820,0.016974,0.000882
Open Porch SF,0.016355,-0.071311,-0.014823,0.163040,0.103760,0.298412,-0.068934,0.198365,0.241748,0.143748,...,0.232912,0.039243,1.000000,-0.059875,-0.009458,0.047548,0.064135,0.077254,0.033651,-0.037467
Enclosed Porch,0.027908,0.162519,-0.022866,0.012758,0.021868,-0.140332,0.071459,-0.374364,-0.220383,-0.110787,...,-0.106272,-0.119136,-0.059875,1.000000,-0.032674,-0.063965,0.092596,0.008773,-0.021324,-0.000505
3Ssn Porch,-0.024975,-0.024894,-0.037956,0.028564,0.016243,0.018240,0.043852,0.015803,0.037412,0.013778,...,0.029458,-0.003967,-0.009458,-0.032674,1.000000,-0.029430,-0.006501,-0.000753,0.027229,0.022668
Screen Porch,0.004307,-0.025735,-0.050614,0.076666,0.055044,0.041615,0.044055,-0.041436,-0.046888,0.065643,...,0.062436,-0.052191,0.047548,-0.063965,-0.029430,1.000000,0.026383,0.007162,0.028169,-0.006116
Pool Area,0.052518,-0.002845,-0.003434,0.173947,0.093775,0.030399,-0.016787,0.002213,-0.011410,0.004617,...,0.053051,0.094156,0.064135,0.092596,-0.006501,0.026383,1.000000,0.011942,-0.042223,-0.052541
Misc Val,-0.006083,-0.008260,-0.029254,0.044476,0.069188,0.005179,0.034056,-0.011011,-0.003132,0.044934,...,0.008466,0.056820,0.077254,0.008773,-0.000753,0.007162,0.011942,1.000000,0.007333,0.008574
Mo Sold,0.133365,-0.050455,0.000350,0.011085,0.003859,0.031103,-0.007295,0.014577,0.018048,-0.000276,...,0.039544,0.016974,0.033651,-0.021324,0.027229,0.028169,-0.042223,0.007333,1.000000,-0.155554
Yr Sold,-0.975993,0.009579,-0.017905,-0.007547,-0.023085,-0.020719,0.031207,-0.013197,0.032652,-0.017715,...,-0.013018,0.000882,-0.037467,-0.000505,0.022668,-0.006116,-0.052541,0.008574,-0.155554,1.000000

In [65]:
fig = px.imshow(
    feature_correlation,
    text_auto=".2f",
    aspect="auto",
    title="Correlation Matrix — Numerical Features"
)

fig.show()

In [66]:
upper_triangle = (
    feature_correlation.where(
        np.triu(
            np.ones(
                feature_correlation.shape
            ),
            k=1
        ).astype(bool)
    )
)

high_correlation_pairs = (
    upper_triangle
    .stack()
    .reset_index()
)

high_correlation_pairs.columns = [
    "Feature_1",
    "Feature_2",
    "Correlation"
]

high_correlation_pairs[
    high_correlation_pairs["Correlation"].abs() >= 0.80
].sort_values(
    "Correlation",
    key=lambda x: x.abs(),
    ascending=False
)

          Feature_1      Feature_2  Correlation
37            Order        Yr Sold    -0.975993
1054    Garage Cars    Garage Area     0.889676
292      Year Built  Garage Yr Blt     0.834849
670     Gr Liv Area  TotRms AbvGrd     0.807772
508   Total Bsmt SF     1st Flr SF     0.800720

In [67]:
from statsmodels.stats.outliers_influence import (
    variance_inflation_factor
)

In [68]:
vif_data = df[numerical_features].copy()

vif_data = vif_data.dropna()

vif_results = pd.DataFrame()

vif_results["Feature"] = vif_data.columns

vif_results["VIF"] = [
    variance_inflation_factor(
        vif_data.values,
        i
    )
    for i in range(vif_data.shape[1])
]

vif_results.sort_values(
    "VIF",
    ascending=False
)

e:\Project_Works\ML_Learn\Ames Housing Prices\venv\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

            Feature           VIF
16  Low Qual Fin SF           inf
17      Gr Liv Area           inf
10     BsmtFin SF 1           inf
11     BsmtFin SF 2           inf
12      Bsmt Unf SF           inf
13    Total Bsmt SF           inf
15       2nd Flr SF           inf
14       1st Flr SF           inf
37          Yr Sold  2.441114e+04
1               PID  1.926718e+01
7        Year Built  5.967168e+00
26    Garage Yr Blt  4.746130e+00
28      Garage Area  4.572822e+00
27      Garage Cars  4.564751e+00
0             Order  4.319044e+00
24    TotRms AbvGrd  4.316178e+00
5      Overall Qual  3.265297e+00
20        Full Bath  2.933315e+00
8    Year Remod/Add  2.628611e+00
22    Bedroom AbvGr  2.283569e+00
21        Half Bath  2.229164e+00
18   Bsmt Full Bath  2.164164e+00
3      Lot Frontage  1.912205e+00
2       MS SubClass  1.704736e+00
6      Overall Cond  1.659213e+00
25       Fireplaces  1.528245e+00
9      Mas Vnr Area  1.514548e+00
23    Kitchen AbvGr  1.485511e+00
4          Lot Area  1.456106e+00
30    Open Porch SF  1.275937e+00
31   Enclosed Porch  1.256161e+00
29     Wood Deck SF  1.228591e+00
19   Bsmt Half Bath  1.158502e+00
34        Pool Area  1.120456e+00
33     Screen Porch  1.088018e+00
35         Misc Val  1.078860e+00
36          Mo Sold  1.048211e+00
32       3Ssn Porch  1.018595e+00

In [69]:
vif_plot = (
    vif_results
    .sort_values(
        "VIF",
        ascending=True
    )
)

fig = px.bar(
    vif_plot,
    x="VIF",
    y="Feature",
    orientation="h",
    title="Variance Inflation Factor — Numerical Features"
)

fig.show()

In [70]:
categorical_summary = pd.DataFrame({
    "Feature": categorical_columns,
    "UniqueCategories": [
        df[column].nunique(
            dropna=False
        )
        for column in categorical_columns
    ],
    "MissingValues": [
        df[column].isna().sum()
        for column in categorical_columns
    ]
})

categorical_summary.sort_values(
    "UniqueCategories",
    ascending=False
)

           Feature  UniqueCategories  MissingValues
8     Neighborhood                28              0
16    Exterior 2nd                17              0
15    Exterior 1st                16              0
41       Sale Type                10              0
9      Condition 1                 9              0
12     House Style                 8              0
31      Functional                 8              0
14       Roof Matl                 8              0
10     Condition 2                 8              0
0        MS Zoning                 7              0
24  BsmtFin Type 1                 7             80
33     Garage Type                 7            157
25  BsmtFin Type 2                 7             81
35     Garage Qual                 6            159
40    Misc Feature                 6           2824
29      Electrical                 6              1
22       Bsmt Cond                 6             80
13      Roof Style                 6              0
32    Fireplace Qu                 6           1422
42  Sale Condition                 6              0
26         Heating                 6              0
21       Bsmt Qual                 6             80
36     Garage Cond                 6            159
20      Foundation                 6              0
11       Bldg Type                 5              0
6       Lot Config                 5              0
23   Bsmt Exposure                 5             83
39           Fence                 5           2358
38         Pool QC                 5           2917
30    Kitchen Qual                 5              0
27      Heating QC                 5              0
17    Mas Vnr Type                 5           1775
19      Exter Cond                 5              0
4     Land Contour                 4              0
3        Lot Shape                 4              0
18      Exter Qual                 4              0
34   Garage Finish                 4            159
2            Alley                 3           2732
5        Utilities                 3              0
37     Paved Drive                 3              0
7       Land Slope                 3              0
1           Street                 2              0
28     Central Air                 2              0

In [71]:
neighborhood_counts = (
    df[feature]
    .value_counts(
        dropna=False
    )
)

neighborhood_counts

Garage Yr Blt
NaN       159
2005.0    142
2006.0    115
2007.0    115
2004.0     99
         ...
1895.0      1
1933.0      1
2207.0      1
1943.0      1
1919.0      1
Name: count, Length: 104, dtype: int64

In [72]:
fig = px.bar(
    neighborhood_counts,
    title="Neighborhood Frequency"
)

fig.show()

In [73]:
neighborhood_price_summary = (
    df.groupby("Neighborhood")["SalePrice"]
    .agg(
        [
            "count",
            "mean",
            "median",
            "std",
            "min",
            "max",
        ]
    )
    .sort_values(
        "median",
        ascending=False
    )
)

neighborhood_price_summary

              count           mean    median            std     min     max
Neighborhood
StoneBr          51  324229.196078  319000.0  119273.020694  130000  591587
NridgHt         166  322018.265060  317750.0   95932.354274  154000  615000
NoRidge          71  330319.126761  302000.0  101444.662927  190000  755000
GrnHill           2  280000.000000  280000.0   70710.678119  230000  330000
Veenker          24  248314.583333  250250.0   65474.949540  150000  385000
Timber           72  246599.541667  232106.5   69326.471547  137500  425000
Somerst         182  229707.324176  225500.0   57437.392588  139000  468000
Crawfor         103  207550.834951  200624.0   65230.183286   90350  392500
CollgCr         267  201803.434457  200000.0   54187.843749  110000  475000
Greens            8  193531.250000  198000.0   21998.554133  155000  214000
ClearCr          44  208662.090909  197500.0   51280.213463  107500  328000
Blmngtn          28  196661.678571  191500.0   29317.511457  156820  264561
Gilbert         165  190646.575758  183000.0   33050.029652  115000  377500
NWAmes          131  188406.908397  181000.0   37687.782531   82500  306000
SawyerW         125  184070.184000  180000.0   48995.503318   67500  320000
Mitchel         114  162226.631579  153500.0   41356.861245   80000  300000
NPkVill          23  140710.869565  143750.0    9340.283679  120000  155000
NAmes           443  145097.349887  140000.0   31882.707229   68000  345000
Landmrk           1  137000.000000  137000.0            NaN  137000  137000
SWISU            48  135071.937500  136200.0   30707.471756   60000  200000
Sawyer          151  136751.152318  135000.0   23130.159033   62383  219000
Blueste          10  143590.000000  130500.0   30158.523763  115000  200000
BrkSide         108  124756.250000  126750.0   35740.935575   39300  223500
Edwards         194  130843.381443  125000.0   48030.405046   35000  415000
OldTown         239  123991.891213  119900.0   44327.104453   12789  475000
IDOTRR           93  103752.903226  106500.0   36493.911013   13100  212300
BrDale           30  105608.333333  106000.0   12144.773839   83000  125500
MeadowV          37   95756.486486   88250.0   20130.564823   71000  151400

In [74]:
fig = px.box(
    df,
    x="Neighborhood",
    y="SalePrice",
    title="SalePrice Distribution by Neighborhood"
)

fig.update_layout(
    xaxis_tickangle=-45
)

fig.show()

In [75]:
categorical_overview = []

for column in categorical_columns:

    categorical_overview.append(
        {
            "Feature": column,
            "UniqueCategories": df[column].nunique(
                dropna=False
            ),
            "MissingValues": df[column].isna().sum(),
            "MostFrequent": df[column].mode(
                dropna=True
            ).iloc[0]
            if not df[column].mode(
                dropna=True
            ).empty
            else np.nan,
            "MostFrequentCount": df[column].value_counts(
                dropna=False
            ).iloc[0],
        }
    )

categorical_overview = pd.DataFrame(
    categorical_overview
)

categorical_overview

,Feature,UniqueCategories,MissingValues,MostFrequent,MostFrequentCount
0,MS Zoning,7,0,RL,2273
1,Street,2,0,Pave,2918
2,Alley,3,2732,Grvl,2732
3,Lot Shape,4,0,Reg,1859
4,Land Contour,4,0,Lvl,2633
5,Utilities,3,0,AllPub,2927
6,Lot Config,5,0,Inside,2140
7,Land Slope,3,0,Gtl,2789
8,Neighborhood,28,0,NAmes,443
9,Condition 1,9,0,Norm,2522
10,Condition 2,8,0,Norm,2900
11,Bldg Type,5,0,1Fam,2425
12,House Style,8,0,1Story,1481
13,Roof Style,6,0,Gable,2321
14,Roof Matl,8,0,CompShg,2887
15,Exterior 1st,16,0,VinylSd,1026
16,Exterior 2nd,17,0,VinylSd,1015
17,Mas Vnr Type,5,1775,BrkFace,1775
18,Exter Qual,4,0,TA,1799
19,Exter Cond,5,0,TA,2549
20,Foundation,6,0,PConc,1310
21,Bsmt Qual,6,80,TA,1283
22,Bsmt Cond,6,80,TA,2616
23,Bsmt Exposure,5,83,No,1906
24,BsmtFin Type 1,7,80,GLQ,859
25,BsmtFin Type 2,7,81,Unf,2499
26,Heating,6,0,GasA,2885
27,Heating QC,5,0,Ex,1495
28,Central Air,2,0,Y,2734
29,Electrical,6,1,SBrkr,2682
30,Kitchen Qual,5,0,TA,1494
31,Functional,8,0,Typ,2728
32,Fireplace Qu,6,1422,Gd,1422
33,Garage Type,7,157,Attchd,1731
34,Garage Finish,4,159,Unf,1231
35,Garage Qual,6,159,TA,2615
36,Garage Cond,6,159,TA,2665
37,Paved Drive,3,0,Y,2652
38,Pool QC,5,2917,Ex,2917
39,Fence,5,2358,MnPrv,2358
40,Misc Feature,6,2824,Shed,2824
41,Sale Type,10,0,WD,2536
42,Sale Condition,6,0,Normal,2413

In [76]:
missing_profile = pd.DataFrame({
    "Feature": df.columns,
    "MissingCount": [
        df[column].isna().sum()
        for column in df.columns
    ],
    "MissingPercentage": [
        df[column].isna().mean() * 100
        for column in df.columns
    ],
    "DataType": [
        df[column].dtype
        for column in df.columns
    ],
    "UniqueValues": [
        df[column].nunique(dropna=True)
        for column in df.columns
    ]
})

missing_profile = (
    missing_profile[
        missing_profile["MissingCount"] > 0
    ]
    .sort_values(
        "MissingPercentage",
        ascending=False
    )
)

missing_profile

           Feature  MissingCount  MissingPercentage DataType  UniqueValues
73         Pool QC          2917          99.556314      str             4
75    Misc Feature          2824          96.382253      str             5
7            Alley          2732          93.242321      str             2
74           Fence          2358          80.477816      str             4
26    Mas Vnr Type          1775          60.580205      str             4
58    Fireplace Qu          1422          48.532423      str             5
4     Lot Frontage           490          16.723549  float64           128
64     Garage Qual           159           5.426621      str             5
65     Garage Cond           159           5.426621      str             5
60   Garage Yr Blt           159           5.426621  float64           103
61   Garage Finish           159           5.426621      str             3
59     Garage Type           157           5.358362      str             6
33   Bsmt Exposure            83           2.832765      str             4
36  BsmtFin Type 2            81           2.764505      str             6
32       Bsmt Cond            80           2.730375      str             5
31       Bsmt Qual            80           2.730375      str             5
34  BsmtFin Type 1            80           2.730375      str             6
27    Mas Vnr Area            23           0.784983  float64           445
48  Bsmt Full Bath             2           0.068259  float64             4
49  Bsmt Half Bath             2           0.068259  float64             3
35    BsmtFin SF 1             1           0.034130  float64           995
37    BsmtFin SF 2             1           0.034130  float64           274
43      Electrical             1           0.034130      str             5
39   Total Bsmt SF             1           0.034130  float64          1058
38     Bsmt Unf SF             1           0.034130  float64          1137
63     Garage Area             1           0.034130  float64           603
62     Garage Cars             1           0.034130  float64             6

In [77]:
fig = px.bar(
    missing_profile.sort_values(
        "MissingPercentage"
    ),
    x="MissingPercentage",
    y="Feature",
    orientation="h",
    title="Missing Value Percentage by Feature"
)

fig.show()

In [78]:
analysis_df = df[
    ["Garage Type", "SalePrice"]
].copy()

analysis_df["GarageType_Missing"] = (
    analysis_df["Garage Type"].isna()
)

analysis_df.groupby(
    "GarageType_Missing"
)["SalePrice"].agg(
    [
        "count",
        "mean",
        "median",
        "std"
    ]
)

                    count           mean    median           std
GarageType_Missing
False                2773  185090.307609  165000.0  79584.836009
True                  157  104949.254777  100000.0  34069.812774

In [79]:
fig = px.box(
    analysis_df,
    x="GarageType_Missing",
    y="SalePrice",
    title="SalePrice by Garage Type Missingness"
)

fig.show()

In [80]:
feature_profile = pd.DataFrame({
    "Feature": df.columns,
    "DataType": [
        str(df[column].dtype)
        for column in df.columns
    ],
    "UniqueValues": [
        df[column].nunique(dropna=True)
        for column in df.columns
    ],
    "MissingCount": [
        df[column].isna().sum()
        for column in df.columns
    ],
    "MissingPercentage": [
        df[column].isna().mean() * 100
        for column in df.columns
    ],
})

In [81]:
feature_profile["Mean"] = np.nan
feature_profile["Median"] = np.nan
feature_profile["Std"] = np.nan
feature_profile["Min"] = np.nan
feature_profile["Max"] = np.nan
feature_profile["Skewness"] = np.nan

In [82]:
for column in numerical_features:

    mask = (
        feature_profile["Feature"]
        == column
    )

    feature_profile.loc[
        mask,
        "Mean"
    ] = df[column].mean()

    feature_profile.loc[
        mask,
        "Median"
    ] = df[column].median()

    feature_profile.loc[
        mask,
        "Std"
    ] = df[column].std()

    feature_profile.loc[
        mask,
        "Min"
    ] = df[column].min()

    feature_profile.loc[
        mask,
        "Max"
    ] = df[column].max()

    feature_profile.loc[
        mask,
        "Skewness"
    ] = df[column].skew()